//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apttus.XAuthor.AppRuntime.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XAuthorRuntimeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XAuthorRuntimeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apttus.XAuthor.AppRuntime.Resources.XAuthorRuntimeResources", typeof(XAuthorRuntimeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ABOUT_btnClose_Text {
            get {
                return ResourceManager.GetString("ABOUT_btnClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apttus X-Author for Excel delivers interaction between Microsoft Excel, Chatter, and Salesforce. Configurable ribbons embedded in Microsoft Excel enable intelligent interaction with Salesforce. The technology allows for activity in a Microsoft Excel document to be shared and fully recorded inside any Structured Data System including Salesforce.
        ///
        ///Microsoft Excel users do not need to go into Salesforce or Chatter to perform any tasks. All tasks, including updating Salesforce data and viewing a Chatter feed ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABOUT_lblAboutDescription_Text {
            get {
                return ResourceManager.GetString("ABOUT_lblAboutDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Information....
        /// </summary>
        internal static string ABOUT_lblCopyrightInfo_Text {
            get {
                return ResourceManager.GetString("ABOUT_lblCopyrightInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string ABOUT_version_Text {
            get {
                return ResourceManager.GetString("ABOUT_version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string CHECKOUTVIEW_AppName_HeaderText {
            get {
                return ResourceManager.GetString("CHECKOUTVIEW_AppName_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string CHECKOUTVIEW_btnCancel_Text {
            get {
                return ResourceManager.GetString("CHECKOUTVIEW_btnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select.
        /// </summary>
        internal static string CHECKOUTVIEW_btnSelect_Text {
            get {
                return ResourceManager.GetString("CHECKOUTVIEW_btnSelect_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocId.
        /// </summary>
        internal static string CHECKOUTVIEW_DocId_HeaderText {
            get {
                return ResourceManager.GetString("CHECKOUTVIEW_DocId_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified By.
        /// </summary>
        internal static string CHECKOUTVIEW_LastModifiedBy_HeaderText {
            get {
                return ResourceManager.GetString("CHECKOUTVIEW_LastModifiedBy_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifiedById.
        /// </summary>
        internal static string CHECKOUTVIEW_LastModifiedById_HeaderText {
            get {
                return ResourceManager.GetString("CHECKOUTVIEW_LastModifiedById_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Application File :.
        /// </summary>
        internal static string CHECKOUTVIEW_lblSearch_Text {
            get {
                return ResourceManager.GetString("CHECKOUTVIEW_lblSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string CHECKOUTVIEW_Locked_HeaderText {
            get {
                return ResourceManager.GetString("CHECKOUTVIEW_Locked_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified On.
        /// </summary>
        internal static string CHECKOUTVIEW_ModifiedOn_HeaderText {
            get {
                return ResourceManager.GetString("CHECKOUTVIEW_ModifiedOn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string CONNENTRY_btnConnect_Text {
            get {
                return ResourceManager.GetString("CONNENTRY_btnConnect_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples:.
        /// </summary>
        internal static string CONNENTRY_label1_Text {
            get {
                return ResourceManager.GetString("CONNENTRY_label1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string CONNENTRY_lblConnectStatus_Text {
            get {
                return ResourceManager.GetString("CONNENTRY_lblConnectStatus_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        internal static string COREADDCUSTROWVIEW_btnAdd_Text {
            get {
                return ResourceManager.GetString("COREADDCUSTROWVIEW_btnAdd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string COREADDCUSTROWVIEW_btnCancel_Text {
            get {
                return ResourceManager.GetString("COREADDCUSTROWVIEW_btnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range [1 - 10,000].
        /// </summary>
        internal static string COREADDCUSTROWVIEW_lblMessage_Text {
            get {
                return ResourceManager.GetString("COREADDCUSTROWVIEW_lblMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of rows.
        /// </summary>
        internal static string COREADDCUSTROWVIEW_lblRows_Text {
            get {
                return ResourceManager.GetString("COREADDCUSTROWVIEW_lblRows_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Name.
        /// </summary>
        internal static string COREAPPBROWSEVIEW_AppName_HeaderText {
            get {
                return ResourceManager.GetString("COREAPPBROWSEVIEW_AppName_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string COREAPPBROWSEVIEW_btnCancel_Text {
            get {
                return ResourceManager.GetString("COREAPPBROWSEVIEW_btnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string COREAPPBROWSEVIEW_btnSearch_Text {
            get {
                return ResourceManager.GetString("COREAPPBROWSEVIEW_btnSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select.
        /// </summary>
        internal static string COREAPPBROWSEVIEW_btnSelect_Text {
            get {
                return ResourceManager.GetString("COREAPPBROWSEVIEW_btnSelect_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Apps.
        /// </summary>
        internal static string COREAPPBROWSEVIEW_chkMyApps_Text {
            get {
                return ResourceManager.GetString("COREAPPBROWSEVIEW_chkMyApps_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string COREAPPBROWSEVIEW_Id_HeaderText {
            get {
                return ResourceManager.GetString("COREAPPBROWSEVIEW_Id_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by App Name :.
        /// </summary>
        internal static string COREAPPBROWSEVIEW_lblSearch_Text {
            get {
                return ResourceManager.GetString("COREAPPBROWSEVIEW_lblSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified On.
        /// </summary>
        internal static string COREAPPBROWSEVIEW_ModifiedOn_HeaderText {
            get {
                return ResourceManager.GetString("COREAPPBROWSEVIEW_ModifiedOn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string COREAPPBROWSEVIEW_ResultHeader_HeaderText {
            get {
                return ResourceManager.GetString("COREAPPBROWSEVIEW_ResultHeader_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string COREMULTILINEVIEW_btnCancel_Text {
            get {
                return ResourceManager.GetString("COREMULTILINEVIEW_btnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string COREMULTILINEVIEW_btnSave_Text {
            get {
                return ResourceManager.GetString("COREMULTILINEVIEW_btnSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values:
        ///- one per line
        ///- no commas 
        ///   required.
        /// </summary>
        internal static string COREMULTILINEVIEW_lblValue_Text {
            get {
                return ResourceManager.GetString("COREMULTILINEVIEW_lblValue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string COREWAITWINDOWVIEW_MessageLabel_Text {
            get {
                return ResourceManager.GetString("COREWAITWINDOWVIEW_MessageLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File :.
        /// </summary>
        internal static string FILEINPUTDIALOG_label1_Text {
            get {
                return ResourceManager.GetString("FILEINPUTDIALOG_label1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string INPUTACTLOOKUP_btnGo_Text {
            get {
                return ResourceManager.GetString("INPUTACTLOOKUP_btnGo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string INPUTACTLOOKUP_IDColumn_HeaderText {
            get {
                return ResourceManager.GetString("INPUTACTLOOKUP_IDColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup.
        /// </summary>
        internal static string INPUTACTLOOKUP_label1_Text {
            get {
                return ResourceManager.GetString("INPUTACTLOOKUP_label1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string INPUTACTLOOKUP_ObjectName_HeaderText {
            get {
                return ResourceManager.GetString("INPUTACTLOOKUP_ObjectName_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Fields :.
        /// </summary>
        internal static string LOOKUPSUPPORT_lblSearchFields_Text {
            get {
                return ResourceManager.GetString("LOOKUPSUPPORT_lblSearchFields_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string LOOKUPSUPPORT_linkLabel1_Text {
            get {
                return ResourceManager.GetString("LOOKUPSUPPORT_linkLabel1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string LOOKUPSUPPORT_lnkClear_Text {
            get {
                return ResourceManager.GetString("LOOKUPSUPPORT_lnkClear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type ahead.
        /// </summary>
        internal static string LOOKUPSUPPORT_tabPage1_Text {
            get {
                return ResourceManager.GetString("LOOKUPSUPPORT_tabPage1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type ahead.
        /// </summary>
        internal static string LOOKUPSUPPORT_tabPage2_Text {
            get {
                return ResourceManager.GetString("LOOKUPSUPPORT_tabPage2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string OPTIONSFORM_btnApply_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_btnApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string OPTIONSFORM_btnDone_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_btnDone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated?.
        /// </summary>
        internal static string OPTIONSFORM_chkProxyAuthenticated_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_chkProxyAuthenticated_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store session token locally?.
        /// </summary>
        internal static string OPTIONSFORM_chkSaveTokenLocally_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_chkSaveTokenLocally_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Settings.
        /// </summary>
        internal static string OPTIONSFORM_groupBox1_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_groupBox1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Settings.
        /// </summary>
        internal static string OPTIONSFORM_groupBox3_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_groupBox3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatter Refresh Settings.
        /// </summary>
        internal static string OPTIONSFORM_grpBoxChatter_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_grpBoxChatter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string OPTIONSFORM_label4_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_label4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatter Refresh Duration:.
        /// </summary>
        internal static string OPTIONSFORM_lblChatterDuration_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_lblChatterDuration_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy address to use:.
        /// </summary>
        internal static string OPTIONSFORM_lblProxyHost_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_lblProxyHost_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string OPTIONSFORM_lblProxyPassword_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_lblProxyPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string OPTIONSFORM_lblProxyPort_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_lblProxyPort_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string OPTIONSFORM_lblProxyUserName_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_lblProxyUserName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual proxy configuration.
        /// </summary>
        internal static string OPTIONSFORM_rbManualProxy_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_rbManualProxy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No proxy.
        /// </summary>
        internal static string OPTIONSFORM_rbNoProxy_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_rbNoProxy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system proxy .
        /// </summary>
        internal static string OPTIONSFORM_rbSystemProxy_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_rbSystemProxy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatter.
        /// </summary>
        internal static string OPTIONSFORM_tabChatter_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_tabChatter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    General   .
        /// </summary>
        internal static string OPTIONSFORM_tabGeneral_Text {
            get {
                return ResourceManager.GetString("OPTIONSFORM_tabGeneral_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string SAVEATTFILENAMEVIEW_btnOK_Text {
            get {
                return ResourceManager.GetString("SAVEATTFILENAMEVIEW_btnOK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename :.
        /// </summary>
        internal static string SAVEATTFILENAMEVIEW_label1_Text {
            get {
                return ResourceManager.GetString("SAVEATTFILENAMEVIEW_label1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SSACTIONVIEW_btnCancel_Text {
            get {
                return ResourceManager.GetString("SSACTIONVIEW_btnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear.
        /// </summary>
        internal static string SSACTIONVIEW_btnClear_Text {
            get {
                return ResourceManager.GetString("SSACTIONVIEW_btnClear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next.
        /// </summary>
        internal static string SSACTIONVIEW_btnNext_Text {
            get {
                return ResourceManager.GetString("SSACTIONVIEW_btnNext_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search.
        /// </summary>
        internal static string SSACTIONVIEW_btnSearch_Text {
            get {
                return ResourceManager.GetString("SSACTIONVIEW_btnSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SSACTIONVIEW_chkSelectAll_Text {
            get {
                return ResourceManager.GetString("SSACTIONVIEW_chkSelectAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Across Filters :.
        /// </summary>
        internal static string SSACTIONVIEW_lblSearch_Text {
            get {
                return ResourceManager.GetString("SSACTIONVIEW_lblSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Filters.
        /// </summary>
        internal static string SSACTIONVIEW_llShowFilters_Text {
            get {
                return ResourceManager.GetString("SSACTIONVIEW_llShowFilters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Grid.
        /// </summary>
        internal static string SSACTIONVIEW_rbSelectAllGrid_Text {
            get {
                return ResourceManager.GetString("SSACTIONVIEW_rbSelectAllGrid_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Salesforce.
        /// </summary>
        internal static string SSACTIONVIEW_rbSelectAllSalesforce_Text {
            get {
                return ResourceManager.GetString("SSACTIONVIEW_rbSelectAllSalesforce_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string SWITCHCONNVIEW_btnClose_Text {
            get {
                return ResourceManager.GetString("SWITCHCONNVIEW_btnClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        internal static string SWITCHCONNVIEW_groupBox1_Text {
            get {
                return ResourceManager.GetString("SWITCHCONNVIEW_groupBox1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please establish a valid connection for each Connection Name below. You can click on the URL example links to paste them into the URL field..
        /// </summary>
        internal static string SWITCHCONNVIEW_lblTopMessage_Text {
            get {
                return ResourceManager.GetString("SWITCHCONNVIEW_lblTopMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string USERINPUTFORM_btnCancel_Text {
            get {
                return ResourceManager.GetString("USERINPUTFORM_btnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string USERINPUTFORM_btnNext_Text {
            get {
                return ResourceManager.GetString("USERINPUTFORM_btnNext_Text", resourceCulture);
            }
        }
    }
}
