//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apttus.XAuthor.AppRuntime.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://na15.salesforce.com/services/Soap/class/Apttus_CPQApi/CPQWebService")]
        public string Apttus_XAuthor_AppRuntime_CPQAPI_CPQWebServiceService {
            get {
                return ((string)(this["Apttus_XAuthor_AppRuntime_CPQAPI_CPQWebServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://na15.salesforce.com/services/Soap/class/AppBuilderCPQSupport")]
        public string Apttus_XAuthor_AppRuntime_CPQSupport_AppBuilderCPQSupportService {
            get {
                return ((string)(this["Apttus_XAuthor_AppRuntime_CPQSupport_AppBuilderCPQSupportService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://na30.salesforce.com/services/Soap/class/Apttus_Config2/PricingWebService")]
        public string Apttus_XAuthor_AppRuntime_PricingWebService_PricingWebServiceService {
            get {
                return ((string)(this["Apttus_XAuthor_AppRuntime_PricingWebService_PricingWebServiceService"]));
            }
        }
    }
}
